apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceAccount.name }}
spec:
  selector:
    app: springboot
  ports:
    - protocol: TCP
      port:  {{ .Values.service.port }}
      targetPort:  {{ .Values.service.port }}
      nodePort: {{ .Values.service.externalPort }}
  type: LoadBalancer