apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceAccount.name }}
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
  